### ISSUE TITLE
Missing reqs for install and error

### ISSUE THREAD

**Issue by pl-ki** [linnarsson-lab/cytograph-shoji#1]
Seems the following requirements are not specified:
numpy==1.21 (API of latest 1.24 has changed to incompatible)
tomotopy
scanpy

Still getting error:
>>> import cytograph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pipeline/git/cytograph-shoji/cytograph/__init__.py", line 14, in <module>
    from .visualization import *
  File "/home/pipeline/git/cytograph-shoji/cytograph/visualization/__init__.py", line 17, in <module>
    from .plot_karyotype import PlotKaryotype
ImportError: cannot import name 'PlotKaryotype' from 'cytograph.visualization.plot_karyotype' (/home/pipeline/git/cytograph-shoji/cytograph/visualization/plot_karyotype.py)
 (using python 3.8.5)

**Comment by pl-ki** [comment]
Seems PlotKaryotype has been replaced by PlotHmmKaryotype in plot_karyotype.py but this is not reflected in corresponding __init__.py
